CREATE TABLE roles
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE users
(
    id                      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    firstname               VARCHAR(100) NOT NULL,
    lastname                VARCHAR(100) NOT NULL,
    email                   VARCHAR(100) NOT NULL,
    username                VARCHAR(100) NOT NULL,
    phone                   VARCHAR(20)  NOT NULL,
    password                VARCHAR(255) NOT NULL,
    account_non_expired     BOOLEAN      NOT NULL,
    account_non_locked      BOOLEAN      NOT NULL,
    credentials_non_expired BOOLEAN      NOT NULL,
    enabled                 BOOLEAN      NOT NULL,
    organization_id         BIGINT,
    status                  SMALLINT     NOT NULL,
    role_id                 BIGINT,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

ALTER TABLE users
    ADD CONSTRAINT uc_d41b903a377589c1f00330dcf UNIQUE (id, role_id);

ALTER TABLE roles
    ADD CONSTRAINT uc_fd322f7161fc2fbfed95c3840 UNIQUE (name);

ALTER TABLE users
    ADD CONSTRAINT uc_users_email UNIQUE (email);

ALTER TABLE users
    ADD CONSTRAINT uc_users_phone UNIQUE (phone);

ALTER TABLE users
    ADD CONSTRAINT FK_USERS_ON_ROLE FOREIGN KEY (role_id) REFERENCES roles (id);